name: linear-regression-env
channels:
  - defaults
dependencies:
  - python=3.11
  - scikit-learn
  - numpy
  - pandas
  - scipy
  - joblib
  - pip
  - pip:
    - azureml-inference-server-http
    - python-dotenv
